"""Password Policy discovery models.

Three tables:
  - password_policies         Canonical normalized policy snapshots, one row per
                              (asset, policy_source, policy_name).  An asset may
                              have several rows (e.g. local + domain + FGPP).
                              is_effective_policy=True marks the one that wins
                              for most accounts on that asset.

  - account_policy_exceptions Per-account deviations from the asset-level
                              effective policy (e.g. password_never_expires,
                              CHECK_POLICY OFF, privileged account under weaker
                              policy, etc.).

  - password_policy_findings  Risk findings generated by the rules engine.
                              Linked to a policy and optionally to an exception
                              and/or an account.
"""
from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import (
    Boolean,
    DateTime,
    ForeignKey,
    SmallInteger,
    String,
    Text,
    UniqueConstraint,
)
from sqlalchemy.dialects.postgresql import ENUM as PgEnum
from app.db_types import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db import Base
from app.models._base import created_at, updated_at, uuid_pk
from app.models.enums import (
    Platform,
    PolicyFindingReviewState,
    PolicyFindingSeverity,
    PolicyScope,
    PolicySource,
)


class PasswordPolicy(Base):
    """Canonical password policy snapshot for one policy source on one asset.

    Design notes:
      - One asset may have multiple rows (local, domain, FGPP, etc.).
      - is_effective_policy marks which row applies to most accounts.
      - For FGPP / PSO targets, applies_to describes the scope (group / account).
      - None for a numeric field means "not collected / unknown", not "zero".
      - confidence_score (0–100) reflects collection completeness:
          100 = all fields reliably collected
           75 = most fields collected, a few inferred
           50 = partial collection
           25 = source identified, most settings unavailable
            0 = policy existence inferred, no settings visible
    """

    __tablename__ = "password_policies"
    __table_args__ = (
        UniqueConstraint(
            "asset_id", "policy_source", "policy_name",
            name="uq_pwpol_asset_source_name",
        ),
    )

    id: Mapped[uuid.UUID] = uuid_pk()
    asset_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("assets.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    # The discovery job that populated this row (nullable for manual imports)
    job_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("discovery_jobs.id", ondelete="SET NULL"),
        nullable=True,
    )
    platform: Mapped[Platform] = mapped_column(
        PgEnum(Platform, name="platform_enum", create_type=False),
        nullable=False,
        index=True,
    )
    policy_source: Mapped[PolicySource] = mapped_column(
        PgEnum(PolicySource, name="policy_source_enum", create_type=False),
        nullable=False,
        index=True,
    )
    policy_scope: Mapped[PolicyScope] = mapped_column(
        PgEnum(PolicyScope, name="policy_scope_enum", create_type=False),
        nullable=False,
    )

    # Human-readable policy name
    # e.g. "Default Domain Policy", "HardenedFGPP", "/etc/security/pwquality.conf"
    policy_name: Mapped[str | None] = mapped_column(String(255), nullable=True)

    # When multiple policies coexist, which one is actually in effect for
    # most accounts on this asset (True on exactly one row per asset,
    # or None if it cannot be determined).
    is_effective_policy: Mapped[bool] = mapped_column(
        Boolean, nullable=False, default=False, index=True
    )

    # FGPP / PSO target scope; for all other sources this is None.
    # {"type": "group", "name": "Domain Admins", "dn": "CN=...", "precedence": 10}
    # {"type": "account", "name": "svc_backup"}
    applies_to: Mapped[dict | None] = mapped_column(JSONB, nullable=True)

    # Precedence value: higher = more specific / wins over lower values.
    # AD PSOs have explicit precedence; for other sources this may be None.
    precedence: Mapped[int | None] = mapped_column(SmallInteger, nullable=True)

    # ── Core password settings ─────────────────────────────────────────────────
    min_password_length: Mapped[int | None] = mapped_column(SmallInteger, nullable=True)
    complexity_enabled: Mapped[bool | None] = mapped_column(Boolean, nullable=True)
    password_history_count: Mapped[int | None] = mapped_column(SmallInteger, nullable=True)
    # Age in days; -1 = "not configured", 0 = no minimum age
    min_password_age_days: Mapped[int | None] = mapped_column(SmallInteger, nullable=True)
    # Age in days; 0 = never expires; -1 = "not configured"
    max_password_age_days: Mapped[int | None] = mapped_column(SmallInteger, nullable=True)
    reversible_encryption_enabled: Mapped[bool | None] = mapped_column(Boolean, nullable=True)

    # ── Lockout settings ───────────────────────────────────────────────────────
    # 0 = never lockout; None = unknown
    lockout_threshold: Mapped[int | None] = mapped_column(SmallInteger, nullable=True)
    # -1 = locked until admin unlocks; None = unknown
    lockout_duration_minutes: Mapped[int | None] = mapped_column(SmallInteger, nullable=True)
    reset_lockout_counter_after_minutes: Mapped[int | None] = mapped_column(
        SmallInteger, nullable=True
    )

    # ── Unix / PAM-specific settings ───────────────────────────────────────────
    dictionary_check_enabled: Mapped[bool | None] = mapped_column(Boolean, nullable=True)
    min_char_classes: Mapped[int | None] = mapped_column(SmallInteger, nullable=True)
    min_uppercase: Mapped[int | None] = mapped_column(SmallInteger, nullable=True)
    min_lowercase: Mapped[int | None] = mapped_column(SmallInteger, nullable=True)
    min_digits: Mapped[int | None] = mapped_column(SmallInteger, nullable=True)
    min_special_chars: Mapped[int | None] = mapped_column(SmallInteger, nullable=True)

    # ── External / federation flags ────────────────────────────────────────────
    # True if policy is enforced by an external system (LDAP, Kerberos, SAML)
    # and cannot be fully inspected from this host.
    external_policy_enforced: Mapped[bool | None] = mapped_column(Boolean, nullable=True)
    # True if a human reviewer should verify what the external policy specifies.
    requires_external_review: Mapped[bool | None] = mapped_column(Boolean, nullable=True)

    # ── Evidence ───────────────────────────────────────────────────────────────
    # Structured evidence map: {setting_key: {value, source_file, command, note}}
    evidence_summary: Mapped[dict | None] = mapped_column(JSONB, nullable=True)
    # FK key / path to the raw discovery result row (probe_key or id string)
    raw_evidence_ref: Mapped[str | None] = mapped_column(String(255), nullable=True)
    # Partial-failure message (e.g. "Could not read FGPP — insufficient permissions")
    collection_error: Mapped[str | None] = mapped_column(String(512), nullable=True)

    # ── Metadata ───────────────────────────────────────────────────────────────
    confidence_score: Mapped[int] = mapped_column(SmallInteger, nullable=False, default=0)
    discovered_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, index=True
    )
    created_at: Mapped[datetime] = created_at()
    updated_at: Mapped[datetime] = updated_at()

    # Relationships
    asset: Mapped["Asset"] = relationship("Asset", lazy="joined", foreign_keys=[asset_id])  # type: ignore[name-defined]
    findings: Mapped[list["PasswordPolicyFinding"]] = relationship(
        "PasswordPolicyFinding",
        back_populates="policy",
        cascade="all, delete-orphan",
        lazy="dynamic",
    )
    exceptions: Mapped[list["AccountPolicyException"]] = relationship(
        "AccountPolicyException",
        back_populates="policy",
        cascade="all, delete-orphan",
        lazy="dynamic",
    )


class AccountPolicyException(Base):
    """Per-account deviation from the asset-level effective password policy.

    Examples:
      - password_never_expires set on a specific AD account
      - SQL login with CHECK_POLICY OFF or CHECK_EXPIRATION OFF
      - Account in a weaker-than-expected policy group
      - Privileged account governed by a weaker FGPP
      - Account under external IdP where local policy visibility is zero
    """

    __tablename__ = "account_policy_exceptions"

    id: Mapped[uuid.UUID] = uuid_pk()
    asset_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("assets.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    account_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("accounts_normalized.id", ondelete="CASCADE"),
        nullable=True,
        index=True,
    )
    # The policy this exception deviates FROM (i.e., what should apply)
    policy_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("password_policies.id", ondelete="SET NULL"),
        nullable=True,
    )

    # Structured exception type key.
    # Allowed values (string enum, not DB enum to stay extensible):
    #   password_never_expires, password_not_required, check_policy_off,
    #   check_expiration_off, lockout_exempt, under_weaker_policy,
    #   privileged_account_weak_policy, under_external_policy,
    #   unknown_effective_policy, service_account_exception,
    #   fgpp_not_applied
    exception_type: Mapped[str] = mapped_column(String(64), nullable=False, index=True)

    description: Mapped[str | None] = mapped_column(String(512), nullable=True)

    # What is ACTUALLY governing this account (e.g. "FGPP:WeakServiceFGPP")
    effective_policy_source: Mapped[str | None] = mapped_column(String(128), nullable=True)
    # What SHOULD be governing this account
    expected_policy_source: Mapped[str | None] = mapped_column(String(128), nullable=True)

    evidence: Mapped[dict | None] = mapped_column(JSONB, nullable=True)

    discovered_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, index=True
    )
    created_at: Mapped[datetime] = created_at()
    updated_at: Mapped[datetime] = updated_at()

    account: Mapped["Account"] = relationship("Account", lazy="joined", foreign_keys=[account_id])  # type: ignore[name-defined]
    policy: Mapped["PasswordPolicy"] = relationship(
        "PasswordPolicy", back_populates="exceptions", foreign_keys=[policy_id]
    )


class PasswordPolicyFinding(Base):
    """Risk finding generated by the password-policy rules engine.

    Each row corresponds to one rule triggering on one policy (or one account
    exception).  The review_state tracks analyst workflow.
    """

    __tablename__ = "password_policy_findings"

    id: Mapped[uuid.UUID] = uuid_pk()
    asset_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("assets.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    account_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("accounts_normalized.id", ondelete="CASCADE"),
        nullable=True,
        index=True,
    )
    policy_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("password_policies.id", ondelete="CASCADE"),
        nullable=True,
        index=True,
    )
    exception_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("account_policy_exceptions.id", ondelete="CASCADE"),
        nullable=True,
    )

    # Unique rule identifier, e.g. "PWPOL-001"
    rule_key: Mapped[str] = mapped_column(String(32), nullable=False, index=True)
    severity: Mapped[PolicyFindingSeverity] = mapped_column(
        PgEnum(PolicyFindingSeverity, name="policy_finding_severity_enum", create_type=False),
        nullable=False,
        index=True,
    )
    title: Mapped[str] = mapped_column(String(255), nullable=False)
    description: Mapped[str] = mapped_column(Text, nullable=False)
    recommendation: Mapped[str | None] = mapped_column(Text, nullable=True)

    # Human-readable scope description, e.g. "All domain users", "Domain Admins group"
    affected_scope: Mapped[str | None] = mapped_column(String(256), nullable=True)

    # Structured evidence captured at the time the rule fired
    evidence: Mapped[dict | None] = mapped_column(JSONB, nullable=True)

    # True when this finding is specifically about an account-level exception
    is_exception_finding: Mapped[bool] = mapped_column(
        Boolean, nullable=False, default=False, index=True
    )

    # ── Analyst review workflow ────────────────────────────────────────────────
    review_state: Mapped[PolicyFindingReviewState] = mapped_column(
        PgEnum(
            PolicyFindingReviewState,
            name="policy_finding_review_state_enum",
            create_type=False,
        ),
        nullable=False,
        default=PolicyFindingReviewState.open,
        index=True,
    )
    reviewed_by: Mapped[str | None] = mapped_column(String(255), nullable=True)
    reviewed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    review_comment: Mapped[str | None] = mapped_column(Text, nullable=True)

    discovered_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, index=True
    )
    created_at: Mapped[datetime] = created_at()

    # Relationships
    policy: Mapped["PasswordPolicy"] = relationship(
        "PasswordPolicy", back_populates="findings", foreign_keys=[policy_id]
    )
